version: "3.8"

services:
  my-target-gtcom-api:
    build: .
    container_name: my-target-gtcom-api
    restart: always
    environment:
      TZ: Europe/Moscow
      ECOMRU_PG_DB_NAME: ${ECOMRU_PG_DB_NAME}
      ECOMRU_PG_HOST: ${ECOMRU_PG_HOST}
      ECOMRU_PG_PORT: ${ECOMRU_PG_PORT}
      ECOMRU_PG_USER: ${ECOMRU_PG_USER}
      ECOMRU_PG_PASSWORD: ${ECOMRU_PG_PASSWORD}
      ECOMRU_PG_SSL_MODE: ${ECOMRU_PG_SSL_MODE}
    volumes:
      - /home/get/logs_all/my_target_gtcom_api/:/app/logs/
    
  nginx:
    container_name: nginx-my-target-gtcom-api
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      -  my-target-gtcom-api
    restart: always
    environment:
      - "TZ=Europe/Moscow"
    ports:
      - 8095:80
      - 4455:443
    volumes:
      - /home/get/cert:/app/cert


    
